package MemoryCatcherApp;


/**
* MemoryCatcherApp/FriendListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 13 November 2014 23:17:47 o'clock GMT
*/

public final class FriendListHolder implements org.omg.CORBA.portable.Streamable
{
  public MemoryCatcherApp.User value[] = null;

  public FriendListHolder ()
  {
  }

  public FriendListHolder (MemoryCatcherApp.User[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MemoryCatcherApp.FriendListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MemoryCatcherApp.FriendListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MemoryCatcherApp.FriendListHelper.type ();
  }

}
