package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryCatcherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 13 November 2014 23:17:47 o'clock GMT
*/

public interface MemoryCatcherOperations 
{
  MemoryCatcherApp.User[] getAllUsers ();
  MemoryCatcherApp.User getUserByName (String name);
  MemoryCatcherApp.User getUserById (int userId);
  boolean addUser (String name, String pass);
  boolean updateUser (MemoryCatcherApp.User user);
  boolean removeUser (int userId);
  MemoryCatcherApp.User[] getAllFriends (int userId);
  boolean addFriend (int user_a, int user_b);
  boolean updateFriend (int user_a, int user_b, boolean active);
  boolean removeFriend (int user_a, int user_b);
  MemoryCatcherApp.Memory[] getAllMemories ();
  MemoryCatcherApp.Memory[] getAllUserMemories (int userId);
  boolean addMemory (int ownerId, String title, String desc);
  boolean updateMemory (MemoryCatcherApp.Memory memory);
  boolean removeMemory (int memoryId);
  MemoryCatcherApp.Resource[] getAllResources (int memoryId);
  boolean addResource (int memoryId, int ownerId, String type, String location);
  boolean updateResource (MemoryCatcherApp.Resource res);
  boolean removeResource (int resId);
} // interface MemoryCatcherOperations
