package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryCatcher.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 13 November 2014 23:17:47 o'clock GMT
*/

public interface MemoryCatcher extends MemoryCatcherOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MemoryCatcher
