package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 13 November 2014 23:17:47 o'clock GMT
*/

public final class MemoryListHolder implements org.omg.CORBA.portable.Streamable
{
  public MemoryCatcherApp.Memory value[] = null;

  public MemoryListHolder ()
  {
  }

  public MemoryListHolder (MemoryCatcherApp.Memory[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MemoryCatcherApp.MemoryListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MemoryCatcherApp.MemoryListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MemoryCatcherApp.MemoryListHelper.type ();
  }

}
