package MemoryCatcherApp;


/**
* MemoryCatcherApp/ResourceListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 13 November 2014 23:17:47 o'clock GMT
*/

public final class ResourceListHolder implements org.omg.CORBA.portable.Streamable
{
  public MemoryCatcherApp.Resource value[] = null;

  public ResourceListHolder ()
  {
  }

  public ResourceListHolder (MemoryCatcherApp.Resource[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MemoryCatcherApp.ResourceListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MemoryCatcherApp.ResourceListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MemoryCatcherApp.ResourceListHelper.type ();
  }

}
