package MemoryCatcherApp;


/**
* MemoryCatcherApp/Resource.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 13 November 2014 23:17:47 o'clock GMT
*/

public final class Resource implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int memoryId = (int)0;
  public int ownerId = (int)0;
  public String type = null;
  public String location = null;
  public String createDate = null;

  public Resource ()
  {
  } // ctor

  public Resource (int _id, int _memoryId, int _ownerId, String _type, String _location, String _createDate)
  {
    id = _id;
    memoryId = _memoryId;
    ownerId = _ownerId;
    type = _type;
    location = _location;
    createDate = _createDate;
  } // ctor

} // class Resource
