package mc;


/**
* mc/_MemoryCatcherImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

public abstract class _MemoryCatcherImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements mc.MemoryCatcher, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _MemoryCatcherImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAllUsers", new java.lang.Integer (0));
    _methods.put ("getUserByName", new java.lang.Integer (1));
    _methods.put ("getUserById", new java.lang.Integer (2));
    _methods.put ("addUser", new java.lang.Integer (3));
    _methods.put ("updateUser", new java.lang.Integer (4));
    _methods.put ("removeUser", new java.lang.Integer (5));
    _methods.put ("getAllFriends", new java.lang.Integer (6));
    _methods.put ("addFriend", new java.lang.Integer (7));
    _methods.put ("updateFriend", new java.lang.Integer (8));
    _methods.put ("removeFriend", new java.lang.Integer (9));
    _methods.put ("getAllMemories", new java.lang.Integer (10));
    _methods.put ("getAllUserMemories", new java.lang.Integer (11));
    _methods.put ("addMemory", new java.lang.Integer (12));
    _methods.put ("updateMemory", new java.lang.Integer (13));
    _methods.put ("removeMemory", new java.lang.Integer (14));
    _methods.put ("getAllResources", new java.lang.Integer (15));
    _methods.put ("addResource", new java.lang.Integer (16));
    _methods.put ("updateResource", new java.lang.Integer (17));
    _methods.put ("removeResource", new java.lang.Integer (18));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // mc/MemoryCatcher/getAllUsers
       {
         mc.User $result[] = null;
         $result = this.getAllUsers ();
         out = $rh.createReply();
         mc.UserListHelper.write (out, $result);
         break;
       }

       case 1:  // mc/MemoryCatcher/getUserByName
       {
         String name = in.read_string ();
         mc.User $result = null;
         $result = this.getUserByName (name);
         out = $rh.createReply();
         mc.UserHelper.write (out, $result);
         break;
       }

       case 2:  // mc/MemoryCatcher/getUserById
       {
         int userId = in.read_long ();
         mc.User $result = null;
         $result = this.getUserById (userId);
         out = $rh.createReply();
         mc.UserHelper.write (out, $result);
         break;
       }

       case 3:  // mc/MemoryCatcher/addUser
       {
         String name = in.read_string ();
         String pass = in.read_string ();
         boolean $result = false;
         $result = this.addUser (name, pass);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // mc/MemoryCatcher/updateUser
       {
         mc.User user = mc.UserHelper.read (in);
         boolean $result = false;
         $result = this.updateUser (user);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // mc/MemoryCatcher/removeUser
       {
         int userId = in.read_long ();
         boolean $result = false;
         $result = this.removeUser (userId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // mc/MemoryCatcher/getAllFriends
       {
         int userId = in.read_long ();
         mc.User $result[] = null;
         $result = this.getAllFriends (userId);
         out = $rh.createReply();
         mc.FriendListHelper.write (out, $result);
         break;
       }

       case 7:  // mc/MemoryCatcher/addFriend
       {
         int user_a = in.read_long ();
         int user_b = in.read_long ();
         boolean $result = false;
         $result = this.addFriend (user_a, user_b);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // mc/MemoryCatcher/updateFriend
       {
         int user_a = in.read_long ();
         int user_b = in.read_long ();
         boolean active = in.read_boolean ();
         boolean $result = false;
         $result = this.updateFriend (user_a, user_b, active);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // mc/MemoryCatcher/removeFriend
       {
         int user_a = in.read_long ();
         int user_b = in.read_long ();
         boolean $result = false;
         $result = this.removeFriend (user_a, user_b);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 10:  // mc/MemoryCatcher/getAllMemories
       {
         mc.Memory $result[] = null;
         $result = this.getAllMemories ();
         out = $rh.createReply();
         mc.MemoryListHelper.write (out, $result);
         break;
       }

       case 11:  // mc/MemoryCatcher/getAllUserMemories
       {
         int userId = in.read_long ();
         mc.Memory $result[] = null;
         $result = this.getAllUserMemories (userId);
         out = $rh.createReply();
         mc.MemoryListHelper.write (out, $result);
         break;
       }

       case 12:  // mc/MemoryCatcher/addMemory
       {
         int ownerId = in.read_long ();
         String title = in.read_string ();
         String desc = in.read_string ();
         boolean $result = false;
         $result = this.addMemory (ownerId, title, desc);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 13:  // mc/MemoryCatcher/updateMemory
       {
         mc.Memory memory = mc.MemoryHelper.read (in);
         boolean $result = false;
         $result = this.updateMemory (memory);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 14:  // mc/MemoryCatcher/removeMemory
       {
         int memoryId = in.read_long ();
         boolean $result = false;
         $result = this.removeMemory (memoryId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 15:  // mc/MemoryCatcher/getAllResources
       {
         int memoryId = in.read_long ();
         mc.Resource $result[] = null;
         $result = this.getAllResources (memoryId);
         out = $rh.createReply();
         mc.ResourceListHelper.write (out, $result);
         break;
       }

       case 16:  // mc/MemoryCatcher/addResource
       {
         int memoryId = in.read_long ();
         int ownerId = in.read_long ();
         String type = in.read_string ();
         String location = in.read_string ();
         boolean $result = false;
         $result = this.addResource (memoryId, ownerId, type, location);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 17:  // mc/MemoryCatcher/updateResource
       {
         mc.Resource res = mc.ResourceHelper.read (in);
         boolean $result = false;
         $result = this.updateResource (res);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 18:  // mc/MemoryCatcher/removeResource
       {
         int resId = in.read_long ();
         boolean $result = false;
         $result = this.removeResource (resId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:mc/MemoryCatcher:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _MemoryCatcherImplBase
