package mc;


/**
* mc/FriendListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

public final class FriendListHolder implements org.omg.CORBA.portable.Streamable
{
  public mc.User value[] = null;

  public FriendListHolder ()
  {
  }

  public FriendListHolder (mc.User[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = mc.FriendListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    mc.FriendListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return mc.FriendListHelper.type ();
  }

}
