package mc;

/**
* mc/MemoryCatcherHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

public final class MemoryCatcherHolder implements org.omg.CORBA.portable.Streamable
{
  public mc.MemoryCatcher value = null;

  public MemoryCatcherHolder ()
  {
  }

  public MemoryCatcherHolder (mc.MemoryCatcher initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = mc.MemoryCatcherHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    mc.MemoryCatcherHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return mc.MemoryCatcherHelper.type ();
  }

}
