package mc;


/**
* mc/Memory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

public final class Memory implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int ownerId = (int)0;
  public String title = null;
  public String desc = null;
  public boolean active = false;
  public String createDate = null;

  public Memory ()
  {
  } // ctor

  public Memory (int _id, int _ownerId, String _title, String _desc, boolean _active, String _createDate)
  {
    id = _id;
    ownerId = _ownerId;
    title = _title;
    desc = _desc;
    active = _active;
    createDate = _createDate;
  } // ctor

} // class Memory
