package mc;


/**
* mc/MemoryListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

public final class MemoryListHolder implements org.omg.CORBA.portable.Streamable
{
  public mc.Memory value[] = null;

  public MemoryListHolder ()
  {
  }

  public MemoryListHolder (mc.Memory[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = mc.MemoryListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    mc.MemoryListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return mc.MemoryListHelper.type ();
  }

}
