package mc;


/**
* mc/MemoryCatcherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

public interface MemoryCatcherOperations 
{
  mc.User[] getAllUsers ();
  mc.User getUserByName (String name);
  mc.User getUserById (int userId);
  boolean addUser (String name, String pass);
  boolean updateUser (mc.User user);
  boolean removeUser (int userId);
  mc.User[] getAllFriends (int userId);
  boolean addFriend (int user_a, int user_b);
  boolean updateFriend (int user_a, int user_b, boolean active);
  boolean removeFriend (int user_a, int user_b);
  mc.Memory[] getAllMemories ();
  mc.Memory[] getAllUserMemories (int userId);
  boolean addMemory (int ownerId, String title, String desc);
  boolean updateMemory (mc.Memory memory);
  boolean removeMemory (int memoryId);
  mc.Resource[] getAllResources (int memoryId);
  boolean addResource (int memoryId, int ownerId, String type, String location);
  boolean updateResource (mc.Resource res);
  boolean removeResource (int resId);
} // interface MemoryCatcherOperations
