package mc;


/**
* mc/MemoryListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

abstract public class MemoryListHelper
{
  private static String  _id = "IDL:mc/MemoryList:1.0";

  public static void insert (org.omg.CORBA.Any a, mc.Memory[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static mc.Memory[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = mc.MemoryHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (mc.MemoryListHelper.id (), "MemoryList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static mc.Memory[] read (org.omg.CORBA.portable.InputStream istream)
  {
    mc.Memory value[] = null;
    int _len0 = istream.read_long ();
    value = new mc.Memory[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = mc.MemoryHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, mc.Memory[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      mc.MemoryHelper.write (ostream, value[_i0]);
  }

}
