package mc;

/**
* mc/ResourceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

public final class ResourceHolder implements org.omg.CORBA.portable.Streamable
{
  public mc.Resource value = null;

  public ResourceHolder ()
  {
  }

  public ResourceHolder (mc.Resource initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = mc.ResourceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    mc.ResourceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return mc.ResourceHelper.type ();
  }

}
