package mc;

/**
* mc/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MemoryCatcherIDL.idl
* 09 November 2014 00:18:25 o'clock GMT
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public mc.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (mc.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = mc.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    mc.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return mc.UserHelper.type ();
  }

}
